### ISSUE TITLE
Votes sometimes don't get shown

### ISSUE THREAD

**Issue by aap007freak** [flatlinee/omphudedit#2]
Not all the time, but sometimes when a vote is called,
I only see %voteissue% instead of the actual vote.
I hope this problem gets fixed soon

**Comment by sigsegv-mvm** [comment]
I don't necessarily think this has anything to do with this particular HUD; that kind of thing is known to happen for some reason from time to time. Don't really know why.

I also see a similar thing fairly often with the HUD element that shows the number of active stickies as demoman. In that case at least, as soon as you launch another sticky, it'll update and display a number instead of whatever percentage-sign placeholder text it shows initially.

**Comment by flatlinee** [comment]
yeah these are both valve issues
